const questions = {
    algorithm: [
        { question: "What is a randomized algorithm?", answer: "A randomized algorithm uses a degree of randomness as part of its logic, often to provide a probabilistic guarantee on running time or solution accuracy." },
        { question: "Describe Monte Carlo algorithms", answer: "Monte Carlo algorithms have a probabilistic guarantee that they give correct answers with a certain probability." },
        { question: "Describe Las Vegas algorithms", answer: "Las Vegas algorithms always produce correct results, but their runtime is probabilistic." },
        { question: "Describe Sherwood algorithms", answer: "Sherwood algorithms are randomized algorithms that aim to balance between Las Vegas and Monte Carlo approaches." },
        { question: "Why do we need local search algorithms?", answer: "Local search algorithms are needed for optimization problems where the search space is too large to be explored exhaustively." },
        { question: "Describe the Tabu search algorithm and the role of Tabu list.", answer: "Tabu search is a local search algorithm that uses a Tabu list to prevent cycling back to recently visited solutions." },
        { question: "Define graph connectivity in an undirected graph.", answer: "A graph is connected if there is a path between any pair of vertices." },
        { question: "When is a directed graph strongly connected?", answer: "A directed graph is strongly connected if there is a path from any vertex to every other vertex." },
        { question: "Describe Breadth-first Search (BFS).", answer: "BFS is an algorithm that explores a graph level by level, starting from a source vertex." },
        { question: "Describe Depth-first Search (DFS).", answer: "DFS explores a graph by going as deep as possible along each branch before backtracking." },
        { question: "Define Mutual reachability in the context of directed graphs.", answer: "Mutual reachability occurs when there are directed paths between two vertices in both directions." },
        { question: "Explain complexity classes.", answer: "Complexity classes categorize problems based on their computational difficulty, such as P, NP, NP-complete, and NP-hard." }
    ],
    reinforcement: [
        { question: "What are the different types of value function approximators that can be used for reinforcement learning? When should we use each type?", answer: "Linear approximators, neural networks, and decision trees are common types. Use linear when features are well-defined and low-dimensional, neural networks for high-dimensional data, and decision trees when interpretability is needed." },
        { question: "Which type of reinforcement learning algorithm—on-policy or off-policy—is generally more sample efficient, and why?", answer: "Off-policy algorithms like Q-learning are more sample efficient because they can learn from stored data and experiences not generated by the current policy." },
        { question: "What are the conditions for SARSA and Q-learning to converge towards optimal policies and value functions?", answer: "SARSA and Q-learning converge if the learning rate decays over time, all state-action pairs are explored, and policies balance exploration and exploitation." },
        { question: "Define the Markov property in the Markov Decision Process (MDP) as the mathematical framework for fully observable reinforcement learning problems.", answer: "The Markov property means the future state depends only on the current state and action, not on past states or actions." },
        { question: "Briefly state the Robbins-Monro conditions for SARSA to converge to the optimal policy.", answer: "The Robbins-Monro conditions require the learning rate to decrease over time but remain positive and summable to ensure convergence." },
        { question: "Estimate the state value function using first-visit Monte-Carlo learning algorithm for states A and B.", answer: "To estimate the state value function, compute the average reward of each state from the episodes where it first occurs. V(A) and V(B) are calculated based on the rewards collected during visits to states A and B." },
        { question: "Explain how the Bellman expectation equation is used in policy iteration for solving MDPs.", answer: "The Bellman expectation equation updates the value function by taking the expectation of rewards and future values under the current policy, used iteratively in policy iteration to improve policies." },
        { question: "Determine the optimal value function V* for each non-terminal state in an MDP with a discount factor of 1.", answer: "The optimal value function V* for each non-terminal state is 1 since all paths eventually lead to the terminal state, and the discount factor of 1 implies no discounting of future rewards." }
    ],
    foundational: [
        { question: "For a given labeled database for classification, you train three networks to convergence (no errors on the database). Do the networks have identical complexity? Explain.", answer: "No, the networks may have different architectures or hyperparameters, leading to different complexities even if they achieve the same performance on the training set." },
        { question: "Explain what the complexity of a sequence expresses and why long sequences may have low complexity.", answer: "Sequence complexity measures the unpredictability of the sequence. Long sequences may have regular or repetitive patterns, reducing their overall complexity." },
        { question: "Do you need humans for state-of-the-art LLM performance in terms of human preference (e.g., non-offensive text generation)?", answer: "Yes, human feedback is critical in fine-tuning LLMs to align with human preferences, ensuring outputs like non-offensive text generation." },
        { question: "Explain the need for both a reward model and a KL-divergence measure to implement preference optimization.", answer: "A reward model captures human preferences, while KL-divergence ensures that the model stays close to the base language model, balancing quality and safety." },
        { question: "Explain the generation of text by chatbots such as ChatGPT and Gemini (explain only inference).", answer: "During inference, the model generates text by predicting the next word or token in a sequence based on its learned patterns from training data." },
        { question: "Explain how you would use the query, key, and value in cross-attention and provide an example application.", answer: "In cross-attention, the query comes from one modality (e.g., text), and keys/values from another (e.g., images), allowing the model to focus on relevant parts of the input for tasks like image captioning." },
        { question: "How would you use scaling laws in the development of a new LLM?", answer: "Scaling laws help predict performance improvements with larger models or datasets, guiding resource allocation for developing more capable LLMs." },
        { question: "Can BERT be run in parallel at inference time? How about ChatGPT?", answer: "BERT can be parallelized as it processes all tokens simultaneously, while ChatGPT's autoregressive nature limits parallelization during inference." },
        { question: "What is the purpose of BERT? Provide an application.", answer: "BERT is designed for understanding text by encoding context from both directions. Applications include question answering and sentiment analysis." },
        { question: "Self-attention uses softmax, which is of the form exp(ai) / SUMj exp(aj). What is the purpose of the exponential function in softmax? Can you think of an alternative?", answer: "The exponential function amplifies differences between values, helping focus attention on the most relevant parts. Alternatives include logistic or linear transformations, but they might lack this sharp focus." }
    ],
    cnn: [
        { question: "Explain how the discriminator in a GAN works.", answer: "The discriminator in a GAN classifies whether an input image is real or fake, helping guide the generator by providing feedback during training." },
        { question: "How does the adversarial loss function guide the training of GANs?", answer: "The adversarial loss function encourages the generator to produce realistic images and helps the discriminator improve at distinguishing real from fake images." },
        { question: "What is the key feature that distinguishes CycleGAN from traditional GANs?", answer: "CycleGAN can perform image-to-image translation without paired data by using a cycle consistency loss that ensures the translation can be reversed." },
        { question: "Why are two discriminators used in CycleGAN?", answer: "CycleGAN uses two discriminators to independently evaluate the realism of the forward and backward image transformations." },
        { question: "What is the primary difference between a VAE and a traditional autoencoder?", answer: "A VAE introduces probabilistic elements to the encoding process, allowing it to generate new data by sampling from a learned latent space." },
        { question: "Why does a VAE use reparameterization during training?", answer: "Reparameterization allows gradients to flow through the stochastic sampling process, enabling backpropagation to update the network parameters." },
        { question: "What advantage does a VAE have in generating new images compared to a standard autoencoder?", answer: "A VAE can generate more diverse and realistic images because it learns a continuous, smooth latent space rather than deterministic encodings." },
        { question: "Describe the mathematical steps involved in computing the latent variable z using the re-parameterization trick in VAEs.", answer: "z = μ + σ * ε, where μ and σ are the mean and variance predicted by the encoder, and ε is random noise sampled from a standard normal distribution." }
    ]
};

let currentCategory = 'algorithm';
let currentIndex = 0;

function switchCategory(category) {
    currentCategory = category;
    currentIndex = 0;
    updateCard();
}

function updateCard() {
    const categoryTitle = document.getElementById('category-title');
    const questionText = document.getElementById('question-text');
    const answerText = document.getElementById('answer-text');
    
    categoryTitle.textContent = currentCategory.charAt(0).toUpperCase() + currentCategory.slice(1);
    questionText.textContent = questions[currentCategory][currentIndex].question;
    answerText.textContent = questions[currentCategory][currentIndex].answer;
    answerText.classList.add('hidden');
}

function showAnswer() {
    const answerText = document.getElementById('answer-text');
    answerText.classList.remove('hidden');
}

function nextQuestion() {
    currentIndex = (currentIndex + 1) % questions[currentCategory].length;
    updateCard();
}
